# Generated by Django 3.1.4 on 2020-12-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(choices=[('FR', 'French'), ('EN', 'English'), ('ES', 'Spanish'), ('GE', 'German'), ('CN', 'Chinese')], default='FR', max_length=2)),
            ],
        ),
    ]
