# Generated by Django 3.1.4 on 2020-12-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Select a languare for this book', to='catalog.Languages'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='Language',
            field=models.CharField(choices=[('FR', 'French'), ('EN', 'English')], default='FR', max_length=2),
        ),
    ]
