# Generated by Django 3.1.4 on 2020-12-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201227_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='Language',
            field=models.CharField(blank=True, choices=[('F', 'French'), ('E', 'English')], default='F', help_text='Select Book language', max_length=1),
        ),
    ]
