# Generated by Django 3.1.4 on 2020-12-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20201227_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language_book',
            field=models.CharField(blank=True, choices=[('FR', 'French'), ('EN', 'English'), ('GER', 'German'), ('ES', 'Spanish')], default='FR', help_text='Book Language', max_length=3),
        ),
    ]
