# Generated by Django 3.1.4 on 2021-01-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_book_language_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language_book',
            field=models.CharField(blank=True, choices=[('FR', 'French'), ('EN', 'English'), ('GER', 'German'), ('ES', 'Spanish')], default='FR', help_text='Book Language', max_length=3, verbose_name='Language'),
        ),
    ]
